👷🏻‍♀️Roll back deploy if  current one fails in post-receive hook

diff --git a/post-receive b/post-receive
--- a/post-receive
+++ b/post-receive
@@ -1,6 +1,18 @@
 #!/bin/bash
 
-set -e
+trap 'error_handler' ERR
+
+function error_handler {
+  # Guard against $oldrev being set
+  if [ -n $"$oldrev" ]; then
+    echo "🚨 An error occurred, rolling back to previous deployment $oldrev"
+    git --work-tree="$TARGET" --git-dir="$GIT_DIR" checkout -b backup
+    git --work-tree="$TARGET" --git-dir="$GIT_DIR" branch -f master "$oldrev"
+    git --work-tree="$TARGET" --git-dir="$GIT_DIR" checkout master
+    git --work-tree="$TARGET" --git-dir="$GIT_DIR" branch -D backup
+  fi
+  exit 1
+}
 
 # Clone the project as a bare repo, and install this hook at $GIT_DIR/hooks/post-receive
 # Then add git remote locally, e.g. git remote add prod <server>:$TARGET
@@ -18,7 +30,7 @@ do
     then
         echo "Master ref received.  Deploying master branch to production..."
         git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f
-        cd $TARGET
+        cd $TARGET || error_handler
         docker-compose build
         echo "🚀 Deployed $newrev"
     else
